#ifndef GPIO_CONF_H
#define GPIO_CONF_H

#define RELAY_OPEN 1
#define RELAY_CLOSED 0

// Relay outputs
#define GPIO_OUT_IGNITION 45
#define GPIO_OUT_STARTER 46
#define GPIO_OUT_MARKER 47
#define GPIO_OUT_HEADLIGHT 48
#define GPIO_OUT_BRAKELIGHT 49
#define GPIO_OUT_LEFT_TURN 50
#define GPIO_OUT_RIGHT_TURN 51
#define GPIO_OUT_HORN 52
#define GPIO_OUT_HIGH_BEAM 53

#endif