#ifndef GPIO_CONF_H
#define GPIO_CONF_H

#define RELAY_OPEN 1
#define RELAY_CLOSED 0

// Relay outputs
#define GPIO_OUT_IGNITION 22
#define GPIO_OUT_STARTER 23
#define GPIO_OUT_MARKER 24
#define GPIO_OUT_HEADLIGHT 25
#define GPIO_OUT_BRAKELIGHT 26
#define GPIO_OUT_LEFT_TURN 27
#define GPIO_OUT_RIGHT_TURN 28
#define GPIO_OUT_HORN 29
#define GPIO_OUT_HIGH_BEAM 30

#endif